asset_path: /home/xiaohuangfeng/sim/isaac-b2-ros2/model/b2_robot.urdf
usd_dir: /home/xiaohuangfeng/sim/isaac-b2-ros2/model
usd_file_name: b2_robot.usd
force_usd_conversion: true
make_instanceable: true
fix_base: false
root_link_name: null
link_density: 0.0
merge_fixed_joints: true
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: force
  target_type: position
  gains:
    stiffness: 100.0
    damping: 10.0
collider_type: convex_hull
self_collision: true
replace_cylinders_with_capsules: false
collision_from_visuals: true